# see the GitHub - Dependabot version updates documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '.'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 4
    reviewers:
      - 'dpgraham4401'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'monthly'
