name: 'Build Docker Image'
# This custom, reusable workflow builds and pushes a Docker image to GitHub Container Registry.

on:
  workflow_call:
    inputs:
      image_name:
        default: 'the-manifest-game'
        type: string
        description: 'The name of the image to build.'
      image_tags:
        default: |
          type=schedule
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
        type: string
        description: 'The tags to apply to the docker images'

jobs:
  build_image:
    name: 'Build Docker Image'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
          tags: ${{ inputs.image_tags }}

      - name: 'Set up QEMU'
        # docker emulation library for cross-architecture images
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        # docker buildx plugin for multi-platform images
        uses: docker/setup-buildx-action@v3

      - name: 'Login to GitHub Image Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push'
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
