name: 'Test Build'
# This workflow builds the manifest game web application

on:
  pull_request:
    branches: [ 'main' ]
  workflow_call:
  push:
    branches: [ 'main' ]
    tags: [ 'v*' ]


jobs:
  test_npm_build:
    name: 'NPM'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20 ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Build Client'
        run: npm run build

  test_image_builds:
    name: 'Image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/the-manifest-game

      - name: 'Build and push'
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64
          context: .
          push: false
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
