name: 'Release Drafter'

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read

jobs:
  update_draft:
    name: 'Update Change Log'
    if: github.repository == 'usepa/the-manifest-game'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Update Release Draft'
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
